research_task:
  description: >
    针对 {topic} 开展深入研究。
    请确保结合当前年份 {current_year}，查找所有有趣且相关的信息。
  expected_output: >
    一份包含 10 条要点的列表，列出关于 {topic} 最相关的信息。
  agent: researcher

reporting_task:
  description: >
    审阅你获得的上下文内容，并将每个主题扩展成完整的报告章节。
    报告应详细且全面，包含所有相关信息。
  expected_output: >
    一篇格式为 markdown 的完整报告，每个主要主题都有对应的详细章节。
    格式为 markdown，但不要包含 '```'。
  agent: reporting_analyst
